switchtolayout;
setanalysis('number of trial modes',10);
setanalysis('search','near n');
setanalysis('use max index',false);
setanalysis('N',4);
setanalysis('calculate group index',true);

#RF_length = 3.5e-3;

# Set slab resistance and pn junction capacitance at zero bias

# Ohm for 1 um length in y direction
Rslab_total = str2num(read('tw_modulator_Rslab_tot.dat'))*1e6;  
setnamed('n','r',Rslab_total*0.5); 
setnamed('p','r',Rslab_total*0.5);
#F for 1 um length in y direction
setnamed('junction','c',1e-6 * 4.1508e-10); 

f = linspace(5e9,60e9,12);
loss = matrix(length(f));
ng = matrix(length(f));
neff = matrix(length(f));
Z0 = matrix(length(f));

for(i=1; i<=12; i=i+1){
    setanalysis('frequency',f(i));
    findmodes;
    loss(i) = getdata('mode1','loss');
    ng(i) = getdata('mode1','ng');
    Z0(i) = getdata('mode1','Z0');
    neff(i) = getdata('mode1','neff');
}

# Visualize and save to files for import to INTERCONNECT
plot(f/1e9,loss/100,'f(GHz)','loss [dB/cm]');
loss = [f,loss];
plot(f/1e9,real(ng),'f(GHz)','group index');
ng = [f,real(ng)];
plot(f/1e9,real(Z0),'f(GHz)','resistance [Ohm]');
plot(f/1e9,imag(Z0),'f(GHz)','reactance [Ohm]');
Z0 = [f,real(Z0),imag(Z0)];
plot(f/1e9,real(neff),'f(GHz)','neff');
neff = [f,neff];
matlabsave("tw_modulator_RF_data",loss,ng,Z0);
savedata("tw_modulator_RF_data", loss, ng, Z0);
write("loss_vs_freq.dat", num2str(loss), "overwrite");
write("ng_vs_freq.dat",   num2str(ng),   "overwrite");
write("Z0_vs_freq.dat",   num2str(Z0),   "overwrite");
write("neff_vs_freq.dat",   num2str(neff),   "overwrite");

write("tw_modulator_RF_data.dat", num2str([loss, ng, Z0]), "overwrite");