switchtolayout();
deleteall();
clear();

# Add charge distribution 
addgridattribute("np density");
set("name","np density");
select("np density");
importdataset("tw_modulator_DC_results.mat");

DefineGeometry_step3;
select('Si wg');
set('grid attribute name', 'np density');

select('Si pad');
set('grid attribute name', 'np density');

SetFDE_step3;
MeshOverride_step3;

# run; 
# findmodes;

switchtolayout();
V_index = 10;
V = linspace(-0.5,4,V_index);

neff = matrix(V_index,1);
ng    = matrix(V_index,1);
loss  = matrix(V_index,1);


filename = "results_voltage_sweep_step3.txt";    

for(i=1; i<=10; i=i+1){
    setnamed('np density','V_cathode_index',i);
    findmodes;
    neff(i) = getdata('mode1','neff');
    ng(i) = getdata('mode1','ng');
    loss(i) = getdata('mode1','loss');
    result = [neff(i),ng(i),loss(i)];
    write(filename,num2str(result));
    # visualize(getresult("mode1","E"));
    switchtolayout;

}

?'Voltage sweep is finished';
dneff = neff - neff(2); # relative change in index wrt. zero bias

L = 3000-6; # set the length of the modulator arm to plot phase shift
la0 = getnamed("MODE","wavelength"); # central wavelength
rel_phase = 2*pi*real(dneff)/la0*L; # phase change
        
write(filename,"Length MMI\tS31\tS41");

#Visualize some quantities of interest
plot(V,real(neff),"Voltage (V)","effective index");
plot(V,real(ng),"Voltage (V)","group index");
plot(V,rel_phase,"Voltage (V)","Phase shift wrt. zero bias (rad.)");


# Save to files for import to INTERCONNECT
neff = [V,real(neff),imag(neff)];
dneff = [V,real(dneff),imag(dneff)];
loss = [V,loss];
ng = [V,real(ng),imag(ng)];
matlabsave("tw_modulator_optical_data",neff,dneff,loss,ng);