addfde();

xspan_fde = 5.85e-6;
zspan_fde = 2e-6;
n_SiO2 = 'SiO2 (Glass) - Palik';
set('solver type' , '2D Y normal');

set("x",0);
set("x span", xspan_fde);

set("y",0);

set("z", 0.5*(pad_height + 0.5*wd_height + 0.5*pad_height ));
set("z span",zspan_fde);

set('define x mesh by', 'number of mesh cells');
set('define z mesh by', 'number of mesh cells');
set('mesh cells x', 100);
set('mesh cells z', 100);

set('x min bc', 'Metal');
set('x max bc', 'Metal');
set('z min bc', 'Metal');
set('z max bc', 'Metal');

set('background material', n_SiO2);

setanalysis('wavelength',1.55e-6);
setanalysis('number of trial modes',5);
setanalysis('search','near n');
setanalysis('use max index',true);
setanalysis('calculate group index',true);